### ISSUE TITLE
travis failing

### ISSUE THREAD

**Issue by aleks-f** [pocoproject/poco#1768]
@zosrothko can you take a look at [this](https://travis-ci.org/pocoproject/poco/jobs/247240624)?
![image](https://user-images.githubusercontent.com/2429093/27579630-7cdd79ec-5b28-11e7-864d-228937dcbed5.png)

**Comment by zosrothko** [comment]
Fixed by PR #1769

**Comment by aleks-f** [comment]
thanks, but still failing for some reason:
![image](https://user-images.githubusercontent.com/2429093/27582036-c90eddae-5b2f-11e7-9ca9-6911a431ee08.png)

**Comment by zosrothko** [comment]
Travis jobs are failing because ODBCTest is using a c++11 feature, aka Default Template argument. Thus either those tests should be moved to the poco-c++11 branch, either they should comply with pre c++11 compilers

```
In file included from src/ODBCTest.h:25:
src/SQLExecutor.h:567:15: error: type-id cannot have a name
                Poco::Int64 IntType
                            ^~~~~~~
src/SQLExecutor.h:565:21: warning: default template arguments for a function
      template are a C++11 extension [-Wc++11-extensions]
        template <typename IntType =
                           ^
src/SQLExecutor.h:581:15: error: no template named 'Tuple'; did you mean
      'Poco::Tuple'?
                std::vector<Tuple<int, double, std::string> > v;
                            ^~~~~
                            Poco::Tuple
/home/travis/build/pocoproject/poco/Foundation/include/Poco/Tuple.h:57:8: note: 
      'Poco::Tuple' declared here
struct Tuple
       ^
In file included from src/ODBCTestSuite.cpp:14:
In file included from src/ODBCDB2Test.h:20:
In file included from src/ODBCTest.h:25:
src/SQLExecutor.h:582:15: error: no template named 'Tuple'; did you mean
      'Poco::Tuple'?
                v.push_back(Tuple<int, double, std::string>(1, 1.5, "3"));
                            ^~~~~
                            Poco::Tuple
/home/travis/build/pocoproject/poco/Foundation/include/Poco/Tuple.h:57:8: note: 
      'Poco::Tuple' declared here
struct Tuple
```
